# Generated by Django 4.1.7 on 2023-06-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filenote',
            name='file_name',
            field=models.CharField(default=2062023, max_length=100),
            preserve_default=False,
        ),
    ]
